### ISSUE TITLE
Icarus server crashes after a while with out of memory error

### ISSUE THREAD

**Issue by fclante** [MasterMNB/icarus-dedicated-server#3]
At first I thought it was my rig that was resource depleted, but after upgrading with an additional 16Gb RAM (32Gb DDR4 3200 G.SKILL AEGIS) I still see these errors in the logs with lots of remaining memory available.

LogNet: Warning: UNetDriver::ProcessRemoteFunction: Remote function MULTI_StopMontage called from actor BP_NPC_Chamois_M_Character_C_2147448041 while actor i "This Error is plastered all over the logs for virtually every kind of actor objects."

LogMemory: Warning: Freeing 33554432 bytes from backup pool to handle out of memory.
LogMemory: Warning: MemoryStats:
AvailablePhysical 24280547328
AvailableVirtual 25303957504
UsedPhysical 8545566720
PeakUsedPhysical 8549249024
UsedVirtual 8504619008
PeakUsedVirtual 8504619008
00e8:err:ntdll:RtlpWaitForCriticalSection section 0000000001162578 "?" wait timed out in thread 00e8, blocked by 0024, retrying (60 sec)
LogWindows: Error: === Critical error: ===
0024:err:eventlog:ReportEventW L"=== Critical error: ==="
0024:err:eventlog:ReportEventW L""
LogWindows: Error:
0024:err:eventlog:ReportEventW L"Fatal error: [File:Unknown] [Line: 197] "
LogWindows: Error: Fatal error: [File:Unknown] [Line: 197]
0024:err:eventlog:ReportEventW L"Ran out of memory allocating 65536 bytes with alignment 0"
LogWindows: Error: Ran out of memory allocating 65536 bytes with alignment 0
0024:err:eventlog:ReportEventW L""
LogWindows: Error:
0024:err:eventlog:ReportEventW L""
LogWindows: Error:
0024:err:eventlog:ReportEventW L""
LogWindows: Error:
0024:err:eventlog:ReportEventW L"PHYSX: (D:\Build\++Fortnite\Sync\Engine\Source\ThirdParty\PhysX3\PxShared\src\foundation\src\PsFoundation.cpp 18 0) eINVALID_OPERATION : Foundation destruction failed due to pending module references. Close/release all depending modules first."
LogPhysicsCore: Error: PHYSX: (D:\Build++Fortnite\Sync\Engine\Source\ThirdParty\PhysX3\PxShared\src\foundation\src\PsFoundation.cpp 180) eINVALID_OPERATION : Foundation destruction failed due to pending module references. Close/release all depending modules first.

**Comment by MasterMNB** [comment]
Hi,
the container uses if no prospect is loaded ~1.5-2.5G RAM, but if the prospect is loaded it gets a usage of ~8G (with minimal build things). I also get a lot of error/warning messages but nothing like that.
Maybe the save file is bugged, a few versions ago the server was really instable.
Or does this happen with a new prospect, or even nothing loaded?

It could also be that you have memory problems, you can test your system with Memtest86+.

**Comment by MasterMNB** [comment]
I don't think that this is a problem of the container itself.
But i would say you were correct to report it here: [6](https://github.com/RocketWerkz/IcarusDedicatedServer/issues/6)
To help RocketWerkz, please add more information what hardware you are using and wich version of the server you were using.
